### ISSUE TITLE
LSP document changes

### ISSUE THREAD

**Issue by DifficultNick** [Microsoft/vscode-languageserver-node#456] opened 2019-01-25 19:59 UTC
Based on [lsp-example extension code](https://github.com/Microsoft/vscode-extension-samples/tree/master/lsp-sample) (I am not sure which of 3 repos I should write this)

If you just uncomment `connection.onDidChangeTextDocument` it won't do anything until you place it after `connection.listen();`.
But then:
1)  `documents.onDidChangeContent` will stop working.
Are `connection.onDidChangeTextDocument` and `documents.onDidChangeContent` mutually exclusive?

2) `documents` also stop changing like `textDocumentSync` was changed to `Incremental`.
I mean that for example in `connection.onCompletion` event `documents.get(_textDocumentPosition.textDocument.uri).getText()` returns only change, not full document text.

I'm sorry if I don't understand anything, but I just wanted to get both: current document content and current cursor position in `connection.onDidChangeTextDocument` and in `connection.onCompletion` events and was surprised by the behaviour I've described. If there any helpful documentation about this I will be grateful for links.

**Comment by dbaeumer** [comment] 2019-01-28 14:18
Let me know if you have additional questions.

**Comment by DifficultNick** [comment] 2019-01-28 19:19
Thanks for direct link.

But I still don't understand how should I deal with such a problem:
server must compute some data:
```ts
getData(actualContent: string, cursor: Position): SpecialData;
```
This data is used to compute completion items, hover items etc. and send them to client.
It's also used to compute some special textEdits for client. So this data should be updated at every document change event.

Can you please explain me if there any way
> to get both: current document content and current cursor position in connection.onDidChangeTextDocument and in connection.onCompletion events

?

**Comment by rcjsuen** [comment] 2019-01-28 20:56
@DifficultNick There is no reason to get the current cursor position when you handle `onDidChangeTextDocument`. You should simply be analyzing the content change and then modifying your internal buffer accordingly so that your server's representation of the file now matches the client's.

If managing all of this is too difficult for you for starters you can always just synchronize with full documents.

Regarding the cursor position for `textDocument/completion`, it will be included in the request so you should just use that directly.

**Comment by DifficultNick** [comment] 2019-01-29 17:53
@rcjsuen, thanks for your answer.

> you can always just synchronize with full documents

The only reason I can't use it is because `contentChanges[0].range` is undefined in `onDidChangeTextDocument` handler if `textDocumentSync` is `Full`.

> You should simply be analyzing the content change and then modifying your internal buffer accordingly so that your server's representation of the file now matches the client's.

Sounds like I should create a document change handler on my own that will do the same as client's one to get the actual content. Of cource it will solve my problem but I thought that there must be some simpler tools to do that.

**Comment by rcjsuen** [comment] 2019-01-29 18:22
@DifficultNick Why do you care about the range if you have the whole document?

I am not aware of any prebuilt features in this library that will handle the buffer synchronization. I ended up just writing my own.

**Comment by DifficultNick** [comment] 2019-01-29 20:35
@rcjsuen I care about range because, as I said above, I need to compute some data based on full document text and current cursor position. I need to send some text edits to client (while typing) under some conditions.

> I ended up just writing my own.

It is a sad way, but if @dbaeumer doesn't advice something, I think this issue can be closed.

Thanks to all.

**Comment by rcjsuen** [comment] 2019-01-29 20:52
@DifficultNick If you have the whole document then the range doesn't matter because you are replacing the entire document from before. If you have a record of the last document then you can calculate the range yourself from that. Since the field is optional you cannot rely on clients sending it to your server.

```TypeScript
const changedUri = params.textDocument.uri;
const lastDocument = documents.get(changedUri);
const lastRange = Range.create(lastDocument.positionAt(0), lastDocument.positionAt(lastDocument.getText().length));
```

I think something like this should do what you want? I haven't tested it but the TypeScript code should look something like that?

I still don't understand why you need the range though. You have the complete document and the cursor position is passed to you in `textDocument/completion` so you should be able to walk backwards (or forward) from the cursor to determine what kind of suggestions you should prompt to the user.

**Comment by DifficultNick** [comment] 2019-01-29 21:42
@rcjsuen I don't need range itself. In `textDocument/completion` there is no problem to get position directly, but in `onDidChangeTextDocument` I just wanted to get it from range. And I need position because completions do not provide the whole functionality for me.

For example, imagine that I need to provide auto tag closing (without any suggestions) inside strings. And `editor.quickSuggestions` is turned off for `strings`. That is why I want compute my custom data (that depends on current position) in `onDidChangeTextDocument` too.

I'm sorry if I was unclear =)

**Comment by rcjsuen** [comment] 2019-01-29 22:17
@DifficultNick Generally speaking, it is up to the client to call the server if it wants the server to do something for the user.

It sounds to me that you may want to setup your `triggerCharacters` in your `CompletionOptions`. What do you think, @dbaeumer?

**Comment by DifficultNick** [comment] 2019-01-30 07:36
@rcjsuen, `onCompletion` won't be called if 
> `editor.quickSuggestions` is turned off for `strings`

so `triggerCharacters` makes no sense here. This option need to be turned off to prevent extension snippets suggestions.

And about this:
> it is up to the client to call the server if it wants the server to do something

It's an another strategy, but if server can handle all events I need, why not use it?
This task seemed very simple: just to get all `contentChanges` and full document content on server when document changes. I still can't believe that it can't be solved using built in features.

**Comment by rcjsuen** [comment] 2019-01-30 11:43
@DifficultNick You're right, if the editor doesn't want suggestions then you're not going to be called.

When does the client ask you to close tags? If `textDocument/completion` isn't called, how are you closing the tags for the user? Or are you listening to `textDocument/didChange` and then simply sending `workspace/applyEdit` requests to the client to close your tags?

If you want both content changes and the entire document in `textDocument/didChange` then you should plead your case in the [Microsoft/language-server-protocol repository](https://github.com/Microsoft/language-server-protocol/).

**Comment by DifficultNick** [comment] 2019-01-30 16:16
@rcjsuen, yes, i want to send edits on ’onDidChangeTextDocument’ event.

Ok, i'll try my luck there.

Thanks once more

**Comment by dbaeumer** [comment] 2019-02-19 12:48
One small clarification: even if the range would be set for full content change sync it would the the range of the full document. Not that part that has actually changed. In addition even in incremental sync you can't deduce a cursor position from the changes. For example the changes could come from a quick fix which touched 20 different parts in the document were at one the cursor is. 

The whole LSP has no notation of a cursor by design (with one small exception which are snippets). The major reason is as @rcjsuen pointed out that the client is responsible to ask questions at a position the client knows is interesting. 

I will close the issue since the current behavior is as expected. Please ping if you disagree.

**Closed by dbaeumer** 2019-02-19 12:48 UTC
Labels: needs more info
