### ISSUE TITLE
How to set the pattern in the filter for multi-root workspaces?

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-languageserver-node#958] opened 2022-05-24 01:52 UTC
The issue I am running into is that, if I trigger formatter on some python file under say `python1` package, it still seems to trigger formatting via the formatter that was set for the root of the workspace. I have provided the exact client option that is being passed to create the language client. I believe i am not setting the pattern right, let me know how it should look like to work for the scenario below.

Repro configuration:
consider `multiroot.code-workspace` file with following structure. There are 3 virtual envs at different levels in the structure.
```
{
    "folders": [
        {
            "path": "notpython" // not a python project folder
        },
        {
            "path": "python1" // the python project folder that contains .venv1
        },
        {
            "path": "python2" // the python project folder that contains .venv2
        },
        {
            "path": "." // the root of the workspace also contains python files and has .venv
        }
    ],
}
```

Each of the folders gets its own LSP based formatter, this is the client config for each folder:
LS Client options used for 'notpython' workspace:
```
{
    "documentSelector": [
        { "scheme": "file", "language": "python", "pattern": "c:\\GIT\\linters\\multiroot\\multipython\\notpython/**" },
        {
            "scheme": "untitled",
            "language": "python",
            "pattern": "c:\\GIT\\linters\\multiroot\\multipython\\notpython/**"
        },
        {
            "scheme": "vscode-notebook",
            "language": "python",
            "pattern": "c:\\GIT\\linters\\multiroot\\multipython\\notpython/**"
        },
        {
            "scheme": "vscode-notebook-cell",
            "language": "python",
            "pattern": "c:\\GIT\\linters\\multiroot\\multipython\\notpython/**"
        }
    ],
    "outputChannel": { "name": "Black Formatter" },
    "traceOutputChannel": { "name": "Black Formatter" },
    "revealOutputChannelOn": 4,
    "initializationOptions": {
        "settings": {
            "workspace": "file:///c%3A/GIT/linters/multiroot/multipython/notpython",
            "trace": "error",
            "args": [],
            "path": [],
            "interpreter": ["c:\\GIT\\linters\\multiroot\\multipython\\.venv\\Scripts\\python.exe"]
        }
    },
    "workspaceFolder": {
        "uri": {
            "$mid": 1,
            "fsPath": "c:\\GIT\\linters\\multiroot\\multipython\\notpython",
            "_sep": 1,
            "external": "file:///c%3A/GIT/linters/multiroot/multipython/notpython",
            "path": "/c:/GIT/linters/multiroot/multipython/notpython",
            "scheme": "file"
        },
        "name": "notpython",
        "index": 0
    }
}
```
LS Client options used for 'python1' workspace:
```
{
    "documentSelector": [
        { "scheme": "file", "language": "python", "pattern": "c:\\GIT\\linters\\multiroot\\multipython\\python1/**" },
        {
            "scheme": "untitled",
            "language": "python",
            "pattern": "c:\\GIT\\linters\\multiroot\\multipython\\python1/**"
        },
        {
            "scheme": "vscode-notebook",
            "language": "python",
            "pattern": "c:\\GIT\\linters\\multiroot\\multipython\\python1/**"
        },
        {
            "scheme": "vscode-notebook-cell",
            "language": "python",
            "pattern": "c:\\GIT\\linters\\multiroot\\multipython\\python1/**"
        }
    ],
    "outputChannel": { "name": "Black Formatter" },
    "traceOutputChannel": { "name": "Black Formatter" },
    "revealOutputChannelOn": 4,
    "initializationOptions": {
        "settings": {
            "workspace": "file:///c%3A/GIT/linters/multiroot/multipython/python1",
            "trace": "error",
            "args": [],
            "path": [],
            "interpreter": ["c:\\GIT\\linters\\multiroot\\multipython\\python1\\.venv1\\Scripts\\python.exe"]
        }
    },
    "workspaceFolder": {
        "uri": {
            "$mid": 1,
            "fsPath": "c:\\GIT\\linters\\multiroot\\multipython\\python1",
            "_sep": 1,
            "external": "file:///c%3A/GIT/linters/multiroot/multipython/python1",
            "path": "/c:/GIT/linters/multiroot/multipython/python1",
            "scheme": "file"
        },
        "name": "python1",
        "index": 1
    }
}

```
LS Client options used for 'python2' workspace:
```
{
    "documentSelector": [
        { "scheme": "file", "language": "python", "pattern": "c:\\GIT\\linters\\multiroot\\multipython\\python2/**" },
        {
            "scheme": "untitled",
            "language": "python",
            "pattern": "c:\\GIT\\linters\\multiroot\\multipython\\python2/**"
        },
        {
            "scheme": "vscode-notebook",
            "language": "python",
            "pattern": "c:\\GIT\\linters\\multiroot\\multipython\\python2/**"
        },
        {
            "scheme": "vscode-notebook-cell",
            "language": "python",
            "pattern": "c:\\GIT\\linters\\multiroot\\multipython\\python2/**"
        }
    ],
    "outputChannel": { "name": "Black Formatter" },
    "traceOutputChannel": { "name": "Black Formatter" },
    "revealOutputChannelOn": 4,
    "initializationOptions": {
        "settings": {
            "workspace": "file:///c%3A/GIT/linters/multiroot/multipython/python2",
            "trace": "error",
            "args": [],
            "path": [],
            "interpreter": ["c:\\GIT\\linters\\multiroot\\multipython\\python2\\.venv2\\Scripts\\python.exe"]
        }
    },
    "workspaceFolder": {
        "uri": {
            "$mid": 1,
            "fsPath": "c:\\GIT\\linters\\multiroot\\multipython\\python2",
            "_sep": 1,
            "external": "file:///c%3A/GIT/linters/multiroot/multipython/python2",
            "path": "/c:/GIT/linters/multiroot/multipython/python2",
            "scheme": "file"
        },
        "name": "python2",
        "index": 2
    }
}
```
LS Client options used for '.' or the root workspace:
```
{
    "documentSelector": [
        { "scheme": "file", "language": "python", "pattern": "c:\\GIT\\linters\\multiroot\\multipython/**" },
        { "scheme": "untitled", "language": "python", "pattern": "c:\\GIT\\linters\\multiroot\\multipython/**" },
        { "scheme": "vscode-notebook", "language": "python", "pattern": "c:\\GIT\\linters\\multiroot\\multipython/**" },
        {
            "scheme": "vscode-notebook-cell",
            "language": "python",
            "pattern": "c:\\GIT\\linters\\multiroot\\multipython/**"
        }
    ],
    "outputChannel": { "name": "Black Formatter" },
    "traceOutputChannel": { "name": "Black Formatter" },
    "revealOutputChannelOn": 4,
    "initializationOptions": {
        "settings": {
            "workspace": "file:///c%3A/GIT/linters/multiroot/multipython",
            "trace": "error",
            "args": [],
            "path": [],
            "interpreter": ["c:\\GIT\\linters\\multiroot\\multipython\\.venv\\Scripts\\python.exe"]
        }
    },
    "workspaceFolder": {
        "uri": {
            "$mid": 1,
            "fsPath": "c:\\GIT\\linters\\multiroot\\multipython",
            "_sep": 1,
            "external": "file:///c%3A/GIT/linters/multiroot/multipython",
            "path": "/c:/GIT/linters/multiroot/multipython",
            "scheme": "file"
        },
        "name": "multipython",
        "index": 3
    }
}

```

**Comment by karthiknadig** [comment] 2022-05-24 02:21
I have tried following styles for the pattern and they don't:
1. `c:\\GIT\\linters\\multiroot\\multipython\\python2/**`
2. `python2/**/*`
3. `**/*` (assuming the workspace folder settings covers the root)

This seems to work:
`c:/GIT/linters/multiroot/multipython/python2/**`

But when you select "format document with" you see this:
![image](https://user-images.githubusercontent.com/3840081/169935165-c1ec8a09-dec3-41c0-9fb1-939d0cb00068.png)

Ideally it should only show one Black Formatter, this is because the pattern for `python2` and `.` (the project root) bot fit the file:
`python2`: pattern `c:/GIT/linters/multiroot/multipython/python2/**`
`.`: pattern `c:/GIT/linters/multiroot/multipython/**`

File where format document was selected:
`c:/GIT/linters/multiroot/multipython/python2/something.py`

**Comment by dbaeumer** [comment] 2022-05-24 09:04
@karthiknadig I am pretty sure this is already how VS Code internally selects the formatter and has nothing to do with LSP itself. 

The problem is indeed that the pattern for root and for a project matches the file.

What I did in ESLint is the following:
- when a files gets signaled as open to the server I register a formatter for exactly that file pattern 
- on close I remove the formatter

That avoids that two patterns match the same file

Let me know if this helps.

**Comment by karthiknadig** [comment] 2022-05-24 16:54
@dbaeumer This really does not work for us, where we do all of the registrations over LSP (in python). This issue is coming from our extension templates work, where we are building templates for linting and formatting extensions that will publish with the goal that everything that linting/formatting needs can be done from python. The idea to get the python community to contribute extensions for their favorite tools as extensions to the VS Code market place. So, in the case of formatting, we register it via the response to the initialize request. On the TS side all we do is initialize and start the server.

So, I think for us if the UI can show that the two registered formatters are indeed coming from different workspace roots that would greatly improve the experience.

PS: How does on open, save, or closed LSP events work in the above scenario? do both LSP servers get the open, save, close notification or just the once that closely matches the pattern? How does the coda action request work in this scenario, will it go to both the servers?

**Comment by karthiknadig** [comment] 2022-05-24 21:29
Also it looks like the patterns don't work 100% of the time on the same code. Running the same code on the same workspace some times it uses the wrong one. This feels like it really depends on which one registers first. Since, each server start as a separate process, it could be that the registration of one of them took a bit longer. But I ran formatting after I saw the logs that all 4 servers had registered formatter.

Server 1 pattern: `c:/GIT/linters/multiroot/multipython/notpython/**`
Server 2 pattern: `c:/GIT/linters/multiroot/multipython/python1/**`
Server 3 pattern: `c:/GIT/linters/multiroot/multipython/python2/**`
Server 4 pattern: `c:/GIT/linters/multiroot/multipython/**`  

Actual:
```
black --stdin-filename c:\GIT\linters\multiroot\multipython\python2\something.py -
CWD Formatter: c:\GIT\linters\multiroot\multipython\python2

black --stdin-filename c:\GIT\linters\multiroot\multipython\something.py -
CWD Formatter: c:\GIT\linters\multiroot\multipython

black --stdin-filename c:\GIT\linters\multiroot\multipython\python1\something.py -
CWD Formatter: c:\GIT\linters\multiroot\multipython   <--- this one should be using python1

```

Expected:
```
black --stdin-filename c:\GIT\linters\multiroot\multipython\python2\something.py -
CWD Formatter: c:\GIT\linters\multiroot\multipython\python2

black --stdin-filename c:\GIT\linters\multiroot\multipython\something.py -
CWD Formatter: c:\GIT\linters\multiroot\multipython

black --stdin-filename c:\GIT\linters\multiroot\multipython\python1\something.py -
CWD Formatter: c:\GIT\linters\multiroot\multipython\python1

```

**Comment by dbaeumer** [comment] 2022-05-25 06:16
Regarding the name: to my knowledge VS Code is using the extension's name to present in the UI. I think you can't name a formatter when registering. To support this you would need to open a request to VS Code.

Regarding the second issue I am not sure I understand this: are you saying that VS Code doesn't present a dialog to pick a formatter. I also think that there is no order in VS Code. So, the first registered one will not be the first one in the UI.

A general question: why are you starting 4 servers for this. In ESLint I only start one even in multi root workspace cases.

**Comment by karthiknadig** [comment] 2022-05-25 07:25
@dbaeumer The issue is basically what you see in the comment here: https://github.com/microsoft/vscode-languageserver-node/issues/958#issuecomment-1136449905 , Server 2 should be used for formatting but server 4 gets used, based on the pattern it should have selected Server 2.

The current design for the formatter is the way you suggest, that is, it uses single server even in multi-root scenario. In my first email about this I had asked you if I can register a formatter for each root, you suggest that it could be possible by setting patterns so I was testing it out.

The problem we are trying to solve is that in the multi-root multi-python scenario, we have to run a separate python process for `project1` and `project2` in the above scenario. We do that right now, and it is not as performant as running a language server for each workspace folder. If the individual LS per workspace folder does not work, then we will have plans to run the additional python processes as sub-process to the main server, and handle it that way.

**Comment by karthiknadig** [comment] 2022-05-27 00:20
@dbaeumer I wanted to add one additional bit here, in the python case, we can have different python environment under each workspace folder. So when I run a single Language Server to handle this scenario, I have to deal with running the linter/formatter as a subprocess for each call. This can be very expensive and slow depending on the python environment. So, having individual LS run for each root, and having them not over step each other would greatly reduce the complexity.

For now, I have the one python environment that starts the LS, then on initialization I am starting all the other environments as subprocesses and communicate with them over JSON-RPC. I have to internally handle sending it to the right process, by pretty much doing what the `pattern` part of the Language Client was supposed to do.

**Comment by dbaeumer** [comment] 2022-05-30 11:34
@karthiknadig 

> The issue is basically what you see in the comment here: https://github.com/microsoft/vscode-languageserver-node/issues/958#issuecomment-1136449905 , Server 2 should be used for formatting but server 4 gets used, based on the pattern it should have selected Server 2.

As I was trying to point out before this is not related to LSP. This is something VS Code does and would be the same when using VS Code's API directly. 

Since the pattern for server 4 matches all patterns for server 1 to 3 this is very likely a general problem. I am pretty sure that such a setup might even cause other problems.

I tried this using the following VS Code API only code:

```typescript
// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
import * as vscode from 'vscode';

// this method is called when your extension is activated
// your extension is activated the very first time the command is executed
export function activate(context: vscode.ExtensionContext) {

	const folders = vscode.workspace.workspaceFolders;
	if (folders === undefined || folders.length < 2) {
		return;
	}

	for (const folder of folders) {
		const filter: vscode.DocumentFilter = {
			pattern:  new vscode.RelativePattern(folder, '**/*.txt')
		};
		vscode.languages.registerDocumentFormattingEditProvider([filter], {
			provideDocumentFormattingEdits: (document, options) => {
				return [];
			}
		});
	}

}

// this method is called when your extension is deactivated
export function deactivate() {}
```

and it results in the same behavior. What I would recommend for now is to open an issue against VS Code that we at least can provide a name when registering a formatter provider so that we can distinguish them in the UI.

**Comment by dbaeumer** [comment] 2022-12-06 14:03
I will close the issue since there is nothing LSP can do about this since it is the behavior exposed by VS Code. It needs to be addressed in VS Code itself.

**Closed by dbaeumer** 2022-12-06 14:03 UTC
