### ISSUE TITLE
Double dash when completing snippet

### ISSUE THREAD

**Issue by robertoaloi** [microsoft/vscode-languageserver-node#714] opened 2020-12-21 14:36 UTC
When interacting with the Erlang LS, the user can trigger completion of a snippet by typing:

```
-rec
```

This will cause the following response from the Erlang Language Server:

```
[Trace - 3:27:24 PM] Received response 'textDocument/completion - (1)' in 374ms.
Result: [
    {
        "insertText": "-record(${1:name}, {${2:field} = ${3:Value} :: ${4:Type}()}).",
        "insertTextFormat": 2,
        "kind": 15,
        "label": "-record"
    }
]
```

Then, VS Code completes the code by adding a double dash:

```
--record(name, {field = Value :: Type()}).
```

This works correctly with the Emacs LSP client, so I suspect this could be an actual bug in the VS Code one.

The correct completion should be:
```
-record(name, {field = Value :: Type()}).
```

**Comment by rcjsuen** [comment] 2020-12-21 15:40
May be possible to workaround this issue by using `textEdit` instead of `insertText` so that there is no ambiguity on the client side.

**Comment by robertoaloi** [comment] 2020-12-25 19:34
@rcjsuen It looks like the underlying issue was that the `label` for the `CompletionItem` was starting with a symbol. `textEdit` may work, but it will require some refactoring from our side.

**Comment by dbaeumer** [comment] 2021-01-04 13:25
This reproduces with native VS Code API. I created https://github.com/microsoft/vscode/issues/113754

**Comment by dbaeumer** [comment] 2021-01-04 15:58
This is the expected behavior in VS Code if `-` is a word delimiter. LSP doesn't enforce a certain filtering and matching behavior if no text edit is used since clients might have different strategies already. So if `-` is a word delimiter you can overrule the matching range using a text edit since it forces a spec'd matching and filtering behavior.

**Comment by dbaeumer** [comment] 2021-01-04 16:03
Tested an edit and it works as expected. I will close the issue since there is IMO nothing to do in the lib. Please ping if you think otherwise.

**Closed by dbaeumer** 2021-01-04 16:03 UTC
Labels: depends on VS Code, needs more info
