### ISSUE TITLE
Use Position and Range classes from 'vscode'

### ISSUE THREAD

**Issue by xAlien95** [microsoft/vscode-languageserver-node#743] opened 2021-02-06 23:57 UTC
The `vscode` module has been replaced by `@types/vscode` and `vscode-test`, however I'm still able to
```ts
import { Position, Range } from 'vscode'
```
which gives classes instead of literals/namespaces. Is it still possible to use those?
I noticed there are various "access points", such as `vscode-languageserver`, `vscode-languageserver-protocol`, `vscode-languageserver-types`, etc. Are those classes still available somewhere? Their methods are really handy and compact.

**Comment by rcjsuen** [comment] 2021-02-07 00:21
@xAlien95 I'm not sure I understand what the issue is here.

1. Is your code available in a public repository somewhere for people to look at?
2. What packages do you currently have defined in your `package.json`? What versions are they?
3. What compiler errors are you seeing?

**Comment by xAlien95** [comment] 2021-02-07 00:57
Thank you for replying @rcjsuen.
1. It's essentially [`vscode-extension-samples/tree/master/lsp-sample`](https://github.com/microsoft/vscode-extension-samples/tree/master/lsp-sample), but with `@types/vscode` installed.
2. The default ones plus `@types/vscode@1.53.0` available in the root package.json.
3. `vscode` cannot be imported in the server portion of the extension, but it can in the client portion:
```ts
// server/src/server.ts

// type-checks but throws a runtime error
import { Range } from 'vscode'
console.log(Range)
```
```
Error: Cannot find module 'vscode'
Require stack:
- /Users/xalien95/Developer/SwiftScript/swiftscript-language-features/server/out/parser/handlers/errorConsecutiveStatements.js
- /Users/xalien95/Developer/SwiftScript/swiftscript-language-features/server/out/parser/handlers/index.js
- /Users/xalien95/Developer/SwiftScript/swiftscript-language-features/server/out/parser/index.js
- /Users/xalien95/Developer/SwiftScript/swiftscript-language-features/server/out/server.js
    at Function._resolveFilename (internal/modules/cjs/loader.js:1019:15)
    at internal/modules/cjs/loader.js:895:27
    at Function._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1079:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/xalien95/Developer/SwiftScript/swiftscript-language-features/server/out/parser/handlers/errorConsecutiveStatements.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:1199:30)
    at Object..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1039:32)
    at internal/modules/cjs/loader.js:932:14 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/xalien95/Developer/SwiftScript/swiftscript-language-features/server/out/parser/handlers/errorConsecutiveStatements.js',
    '/Users/xalien95/Developer/SwiftScript/swiftscript-language-features/server/out/parser/handlers/index.js',
    '/Users/xalien95/Developer/SwiftScript/swiftscript-language-features/server/out/parser/index.js',
    '/Users/xalien95/Developer/SwiftScript/swiftscript-language-features/server/out/server.js'
  ]
}
```

My question is if it is possible to use those classes in the server portion of the extension too. If it is not, I would be fine with rewriting them in my module.

**Comment by rcjsuen** [comment] 2021-02-07 01:02
@xAlien95 Thank you for the additional information.

> Their methods are really handy and compact.

What methods are you interested in? I have gotten by with my language server with solely using the `vscode-languageserver-types`, `vscode-languageserver-protocol` and `vscode-languageserver` libraries.

**Comment by xAlien95** [comment] 2021-02-07 01:14
`Position.translate` and `Range.union` as an example. The provided APIs of `Range` from `vscode-languageserver/node` are just `Range.is` and `Range.create`, same goes with `Position`.

As an aside question: in what `**-types`, `**-protocol` and `**/node` differ? They all expose `Range` and `Location`.

**Comment by rcjsuen** [comment] 2021-02-07 15:32
> `Position.translate` and `Range.union` as an example. The provided APIs of `Range` from `vscode-languageserver/node` are just `Range.is` and `Range.create`, same goes with `Position`.

Ah. I've not really needed such functions so that's why I've gotten by I guess.

> As an aside question: in what `**-types`, `**-protocol` and `**/node` differ? They all expose `Range` and `Location`.

I think they all re-export from the original `vscode-languageserver-types` package.

> Edit: are there reference docs for these modules? I can only see [`vscode` references](https://code.visualstudio.com/api/references/vscode-api#Position) in the Extension API documentation pages.

I don't think so.

**Comment by dbaeumer** [comment] 2021-02-08 08:57
@xAlien95 the VS Code types (import via `vscode`) are not available on the server since they need a VS Code client / desktop to back their implementation.

LSP has its own definitions of Range and Positions since LSP is VS Code independent (you can for example use it with VIM). As a result in the VS Code LSP client you have both the LSP type and the VS Code types. There are converters to convert between the two (available via the LanguageClient).

I am closing the issue since this works as designed.

**Closed by dbaeumer** 2021-02-08 08:57 UTC
