### ISSUE TITLE
Trouble working with DocumentSymbol server-side provider output format

### ISSUE THREAD

**Issue by david-pa** [microsoft/vscode-languageserver-node#1050] opened 2022-08-12 17:42 UTC
I'm trying to write a test file to verify the `DocumentSymbol` provider is working on the server, but the output of `await provider?.provideDocumentSymbols(document, tokenSource.token);` is oddly formatted. When looking at the individual lines/symbols, the formatting for each symbol seems to be a mashup of `DocumentSymbol` and `SymbolInformation`.

```
{
        "name":"cos_instance_crn",
        "detail":"$workitem.bp-iks-cos-storage.outputs.cos_crn",
        "kind":7,
        "range":[{"line":116,"character":12},{"line":118,"character":48}],
        "selectionRange":[{"line":116,"character":12},{"line":118,"character":48}],
        "children":[]
}
```
Above, `range` and `selectionRange` do not match the formatting that `DocumentSymbol` needs, but do match SymbolInformation. However, the `detail` parameter doesn't exist within `SymbolInformation`. I settled for comparing snippets for individual symbols to the overall output as a string, but I'd like to do this with `DocumentSymbol` or `SymbolInformation`, if possible. Is there a proper way to use `DocumentSymbol` or `SymbolInformation` for individual entries in the overall provider output?

**Comment by dbaeumer** [comment] 2022-08-15 09:56
I am not sure I understand this. `DocumentSymbol` is defined like this https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#documentSymbol and the result from above looks totally fine to me.

**Comment by david-pa** [comment] 2022-08-15 13:22
The error I get trying to apply the above output to a new DocumentSymbol is as follows:

> Type '{ line: number; character: number; }[]' is missing the following properties from type 'Range': start, end

This error applies to `range` and `selectionRange`.
The issue is that the output received from the provider is formatted using Range and Position instances within `range` and `selectionRange`.

> inputsSymbol.range = Range.create(Position.create(moduleStartLine, moduleStartChar), Position.create(moduleEndLine, moduleEndChar));
    inputsSymbol.selectionRange = inputsSymbol.range;

You're saying the formatting of the data looks correct, so why is the formatting triggering an error? Is it not proper to use `Position` within `Range` for `range` and `selectionRange`?

**Comment by david-pa** [comment] 2022-08-15 20:27
Additionally, the data I get back from the provider, despite being sent by the server as a nested `DocumentSymbol` instance, doesn't seem to line up with a newly created `DocumentSymbol` containing the same data, which causes it to fail equality tests when trying to verify the contents.

Test `DocumentSymbol`:

```
{
    "name":"logdna_name",
    "detail":"Solution input",
    "kind":19,
    "range":lsclient.Range.create(lsclient.Position.create(0, 0), lsclient.Position.create(0, 0)),
    "selectionRange":lsclient.Range.create(lsclient.Position.create(0, 0), lsclient.Position.create(0, 0)),
    "children":[]
}
```

See expected (new test `DocumentSymbol`) vs. actual (`DocumentSymbol` returned by provider):
<img width="270" alt="Screen Shot 2022-08-15 at 3 17 08 PM" src="https://user-images.githubusercontent.com/108750899/184711232-1996c9da-088a-40c7-affa-fcacf800b63d.png">

**Comment by dbaeumer** [comment] 2022-08-16 07:53
The data returned from `provider?.provideDocumentSymbols(document, tokenSource.token);` is LSP defined data and doesn't conform to the VS Code data. You either need to use the converters of a client to convert them yourself or you need to use the VS Code command API (https://code.visualstudio.com/api/references/commands) if you are interested in the VS Code objects (e.g. `vscode.executeDocumentSymbolProvider`).

I will close the issue since everything you see is by design.

**Closed by dbaeumer** 2022-08-16 07:53 UTC
Labels: info-needed

**Comment by dbaeumer** [comment] 2022-08-17 10:48
There is a difference between the data returned from the server request handler and the data returned from various providers:

- the server always returns LSP defined JSON objects.
- the protocol layer (https://github.com/microsoft/vscode-languageserver-node/blob/8b56a58d0a706bc0cc8e947b42ad135faf488fe3/protocol/src/common/protocol.ts#L1) on the client side uses and returns LSP data
- the LSP client (https://github.com/microsoft/vscode-languageserver-node/blob/8b56a58d0a706bc0cc8e947b42ad135faf488fe3/client/src/common/client.ts#L1) uses either LSP data or VS Code data object (which DON't have the same shape) depending on were you are in the code. But for your scenario something like 
```
const resukt = await client.getFeature(lsclient.DeclarationRequest.method).getProvider(document).provideDeclaration(....)
```

returns VS Code data which doesn't conform to LSP data (I wrongly expressed this the other way around above but it is still the same principal). If you need LSP data you need to convert them back using `client.code2ProtocolConverter`

You might want to have a look here how to write tests using an LSP client which tests VS Code data (https://github.com/microsoft/vscode-languageserver-node/blob/8b56a58d0a706bc0cc8e947b42ad135faf488fe3/client-node-tests/src/integration.test.ts#L593) or here https://github.com/microsoft/vscode-languageserver-node/blob/8b56a58d0a706bc0cc8e947b42ad135faf488fe3/protocol/src/node/test/connection.test.ts#L73 to see test cases that only depend on LSP data.

**Comment by david-pa** [comment] 2022-08-17 16:52
@dbaeumer So, upon looking into this, `client.code2ProtocolConverter` doesn't have a converter to go from LSP DocumentSymbols to VSCode symbols, or vice versa. However, `client.protocol2CodeConverter` has a `asDocumentSymbol` method that converts LSP (`lsclient.DocumentSymbol`) instances into VSCode (`vscode.DocumentSymbol`) instances. Unfortunately, upon applying this method to the test instances and the output from the provider call, I get this error during the equivalency test:
<img width="674" alt="Screen Shot 2022-08-17 at 11 49 00 AM" src="https://user-images.githubusercontent.com/108750899/185197162-691712d9-9907-41d0-ae5e-56d9008b5cdb.png">

They have the exact same data prior to the conversion process, so I would assume any changes that occur happen to both, and I'm not getting errors about specific values lining up, just the general error seen above. Any idea why this might be occurring?

**Comment by dbaeumer** [comment] 2022-08-17 18:16
The converter only offers the method that the LSP client needs. Since it doesn't send document symbols to the server it doesn't need on hence it is not implemented.

As said, if you write client tests you need to assert VS Code types if you write protocol tests you need to assert LSP types. This is how it is implemented right now.
