### ISSUE TITLE
vscode-languageclient Error: Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by shadycuz** [microsoft/vscode-languageserver-node#797] opened 2021-08-11 09:27 UTC
I keep seeing this error in the `Log (Windows)` of vscode. 

```
[2021-08-11 05:10:28.048] [renderer7] [error] Illegal argument: line must be non-negative: Error: Illegal argument: line must be non-negative
	at D (/home/shadycuz/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/out/vs/server/remoteExtensionHostProcess.js:5:1232)
	at new b (/home/shadycuz/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/out/vs/server/remoteExtensionHostProcess.js:78:17952)
	at new b (/home/shadycuz/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/out/vs/server/remoteExtensionHostProcess.js:78:17347)
	at R (/home/shadycuz/repos/dsty/groovy-guru/dist/extension.js:1:173470)
	at C (/home/shadycuz/repos/dsty/groovy-guru/dist/extension.js:1:173543)
	at K (/home/shadycuz/repos/dsty/groovy-guru/dist/extension.js:1:177837)
	at /home/shadycuz/repos/dsty/groovy-guru/dist/extension.js:1:183244
	at Array.map (<anonymous>)
	at Object.asSymbolInformations (/home/shadycuz/repos/dsty/groovy-guru/dist/extension.js:1:183236)
	at /home/shadycuz/repos/dsty/groovy-guru/dist/extension.js:1:109293
	at async c.provideDocumentSymbols (/home/shadycuz/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/out/vs/server/remoteExtensionHostProcess.js:85:161482)
```

I have tried running my extension in debug mode with `Caught Exceptions` and `Uncaught Exceptions` but it seems like this doesn't trigger the breakpoint.

I have tracked it down to this in the minified extension code:
```js
registerLanguageProvider(e){const t={provideDocumentSymbols:(e,t)=>{const n=this._client,i=(e,t)=>n.sendRequest(r.DocumentSymbolRequest.type,n.code2ProtocolConverter.asDocumentSymbolParams(e),t).then((e=>{if(null!==e){if(0===e.length)return[];{let t=e[0];return r.DocumentSymbol.is(t)?n.protocol2CodeConverter.asDocumentSymbols(e):n.protocol2CodeConverter.asSymbolInformations(e)}}})
```

This is the only place I use the protocol2CodeConverter in my extension: 

```ts
let clientOptions: LanguageClientOptions = {
          documentSelector: [{ scheme: "file", language: "groovy" }],
          synchronize: {
            configurationSection: "groovy",
          },
          uriConverters: {
            code2Protocol: (value: vscode.Uri) => {
              if (/^win32/.test(process.platform)) {
                //drive letters on Windows are encoded with %3A instead of :
                //but Java doesn't treat them the same
                return value.toString().replace("%3A", ":");
              } else {
                return value.toString();
              }
            },
            //this is just the default behavior, but we need to define both
            protocol2Code: (value) => vscode.Uri.parse(value),
          },
        };
```

I'm not exactly sure where this error is coming from (my code) or the libraries code, or what it causing it.

**Comment by dbaeumer** [comment] 2021-08-11 12:36
The exception is actually coming from VS Code itself. The problem is that a server send a `SymbolInformation` with a negative line number which is against the protocol. So there is little the library or VS Code can do.

Closing the issue. Please ping if you feel otherwise.

**Closed by dbaeumer** 2021-08-11 12:36 UTC

**Comment by shadycuz** [comment] 2021-08-11 12:58
@rcjsuen

> So this is 100% reproducible for you, correct?  

yeah I can clear the log file, then change tabs and go back to my code and the log file has the error again

> It sounds like the breakpoint is not working well for you, but is it reproducible in debug mode or only in the regular case as an installed extension?  

I see the error in the log file in regular use and when running the extension on a remote extension host.

> When the bug occurs, do you have an editor open? If yes, what is the content of the opened file? Is GroovyLanguageServer/groovy-language-server the language server you are using?  

Yeah the error happens when I open some groovy code. That is the LS, [GroovyLanguageServer/groovy-language-server](https://github.com/GroovyLanguageServer/groovy-language-server) is what I'm using.

> The exception is actually coming from VS Code itself. The problem is that a server send a SymbolInformation with a negative line number which is against the protocol. So there is little the library or VS Code can do.  

Yeah if its from the LanguageServer then I will attempt to track it down there.
