### ISSUE TITLE
Server still running after calling client.stop()?

### ISSUE THREAD

**Issue by mastevb** [microsoft/vscode-languageserver-node#850] opened 2021-11-15 03:34 UTC
I've got the following code in my extension
```
	// create language client and launch server
	const pythonMain = context.asAbsolutePath(
		path.join('src', 'server', 'main.py')
	);
	const args = [pythonMain];
	// Add debug options here if needed
	const serverOptions: ServerOptions = { command: pythonInterpreter, args };
	const clientOptions: LanguageClientOptions = {
		documentSelector: [
			{ scheme: "file", language: "antimony" },
		],
	};
	// Create the language client and start the client.
	client = new LanguageClient(
		'AntimonyLanguage',
		'Antimony Language Server',
		serverOptions,
		clientOptions
	);
	// Start the client. This will also launch the server
	const clientDisposable = client.start();
	context.subscriptions.push(clientDisposable);
```
and
```
export function deactivate(): Thenable<void> | undefined {
	if (!client) {
		return undefined;
	}
	// shut down the language client
	return client.stop();
}
```
I've noticed that when I run my extension in debugging mode, even after I quit the extension I can still see the python process in my task manager, and if I run my extension 10 times, there will be 10 processes.
Am I doing anything wrong?

**Comment by dbaeumer** [comment] 2021-11-15 09:47
Your server gets an exit notification which you need to handle and exit the process. Do you do that ?

**Comment by mastevb** [comment] 2021-11-16 00:01
> Your server gets an exit notification which you need to handle and exit the process. Do you do that ?

Where and how should I do that? Sorry I'm very new to extension development, and I usually just do the control command to kill a server.

**Comment by mastevb** [comment] 2021-11-16 07:02
Also, one thing I've noticed is that, if I click on "x" in the window generated by the VS Code debugger, it terminates the extension but leaves the server running. If I click on the square "Stop", the server process gets killed.
Is this expected behavior?

**Comment by dbaeumer** [comment] 2021-11-16 08:49
It all depends on how the server is started. If it is running in detached mode then it outlives the VS Code window. This is by design.

Look here for the exit notification: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#exit

**Comment by mastevb** [comment] 2021-11-16 22:39
> It all depends on how the server is started. If it is running in detached mode then it outlives the VS Code window. This is by design.
> 
> Look here for the exit notification: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#exit

Thanks for the input. The thing that confuses me is that, when I close the window (which also terminates the extension), the process won't be exited, but if I stop the extension without closing the window, the process is terminated. Is this by design tho?

**Comment by dbaeumer** [comment] 2021-11-18 14:24
I actually don't know if the debugger does anything special. Was the debugger attached to the server?

**Comment by vain0x** [comment] 2021-12-07 08:54
[lsp-sample-repro.zip](https://github.com/microsoft/vscode-languageserver-node/files/7666843/lsp-sample-repro.zip) (Note this can write a file to your home directory.)

I encountered similar issue and made a reproduction above.

The code is based on "lsp-sample" in "vscode-extension-samples" repository.
(current main branch, commit hash: ac9bbf2e743ff0a25ebc82095c77b7c0a0fb4914)

Differences:

- server starts as subprocess
- use stdio for connection
- client repeatedly starts and stops (with several second interval)
- server writes a file to home directory when it received exit notification

Complete diff:

<details>
diff --git a/lsp-client-repro/lsp-sample-repro/client/src/extension.ts b/lsp-client-repro/lsp-sample-repro/client/src/extension.ts
index 374a1b5..0928433 100644
--- a/lsp-client-repro/lsp-sample-repro/client/src/extension.ts
+++ b/lsp-client-repro/lsp-sample-repro/client/src/extension.ts
@@ -3,6 +3,7 @@
  * Licensed under the MIT License. See License.txt in the project root for license information.
  * ------------------------------------------------------------------------------------------ */
 
+import * as assert from "assert"
 import * as path from 'path';
 import { workspace, ExtensionContext } from 'vscode';
 
@@ -22,27 +23,32 @@ export function activate(context: ExtensionContext) {
 	);
 	// The debug options for the server
 	// --inspect=6009: runs the server in Node's Inspector mode so VS Code can attach to the server for debugging
-	const debugOptions = { execArgv: ['--nolazy', '--inspect=6009'] };
+	// const debugOptions = { execArgv: ['--nolazy', '--inspect=6009'] };
 
 	// If the extension is launched in debug mode then the debug server options are used
 	// Otherwise the run options are used
 	const serverOptions: ServerOptions = {
-		run: { module: serverModule, transport: TransportKind.ipc },
-		debug: {
-			module: serverModule,
-			transport: TransportKind.ipc,
-			options: debugOptions
-		}
+		// run: { module: serverModule, transport: TransportKind.ipc },
+		// debug: {
+		// 	module: serverModule,
+		// 	transport: TransportKind.ipc,
+		// 	options: debugOptions
+		// }
+		command: "node",
+		args: [
+			serverModule,
+			"--stdio",
+		],
 	};
 
 	// Options to control the language client
 	const clientOptions: LanguageClientOptions = {
 		// Register the server for plain text documents
 		documentSelector: [{ scheme: 'file', language: 'plaintext' }],
-		synchronize: {
-			// Notify the server about file changes to '.clientrc files contained in the workspace
-			fileEvents: workspace.createFileSystemWatcher('**/.clientrc')
-		}
+		// synchronize: {
+		// 	// Notify the server about file changes to '.clientrc files contained in the workspace
+		// 	fileEvents: workspace.createFileSystemWatcher('**/.clientrc')
+		// }
 	};
 
 	// Create the language client and start the client.
@@ -54,9 +60,50 @@ export function activate(context: ExtensionContext) {
 	);
 
 	// Start the client. This will also launch the server
-	client.start();
+	// client.start();
+
+	// -- new code --
+	client.onDidChangeState(e => {
+		console.log("didChangeState", e.oldState, "->", e.newState)
+	})
+
+	let active = true
+	context.subscriptions.push({
+		dispose: () => {
+			console.log("disposed")
+			active = false
+		}
+	})
+
+	const loop = async () => {
+		while (active) {
+			console.log("starts client and waits ready")
+			assert(client.needsStart())
+			client.start()
+			await client.onReady()
+			assert(!client.needsStart())
+
+			console.log("waits for 3 seconds")
+			await delay(3000)
+
+			console.log("stops client")
+			assert(client.needsStop())
+			await client.stop()
+			// await delay(2000 + 100)
+			assert(!client.needsStop())
+			console.log("client stopped")
+
+			console.log("waits for 2 seconds")
+			await delay(2000)
+		}
+
+		console.log("no longer active")
+	}
+	loop().catch(err => console.error("error", err))
 }
 
+const delay = (n: number) => new Promise<void>(resolve => setTimeout(resolve, n))
+
 export function deactivate(): Thenable<void> | undefined {
 	if (!client) {
 		return undefined;
diff --git a/lsp-client-repro/lsp-sample-repro/server/src/server.ts b/lsp-client-repro/lsp-sample-repro/server/src/server.ts
index afd81c3..42cd705 100644
--- a/lsp-client-repro/lsp-sample-repro/server/src/server.ts
+++ b/lsp-client-repro/lsp-sample-repro/server/src/server.ts
@@ -2,6 +2,10 @@
  * Copyright (c) Microsoft Corporation. All rights reserved.
  * Licensed under the MIT License. See License.txt in the project root for license information.
  * ------------------------------------------------------------------------------------------ */
+import * as fs from "fs"
+import * as os from "os"
+import * as path from "path"
+
 import {
 	createConnection,
 	TextDocuments,
@@ -222,6 +226,11 @@ connection.onCompletionResolve(
 	}
 );
 
+connection.onExit(() => {
+	fs.appendFileSync(path.join(os.homedir(), "lsp-sample-server.log"), "received exit notification\n")
+	process.exit(0)
+})
+
 // Make the text document manager listen on the connection
 // for open, change and close text document events
 documents.listen(connection);

</details>

## What happened

Client emits an error message after client.stop is called.

<details>
<summary>output</summary>
(node:30242) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)
starts client and waits ready
didChangeState 1 -> 3
didChangeState 3 -> 2
waits for 3 seconds
stops client
didChangeState 2 -> 1
client stopped
waits for 2 seconds
rejected promise not handled within 1 second: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
stack trace: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
	at Socket.write (internal/streams/writable.js:292:11)
	at $HOME/lsp-client-repro/lsp-sample-repro/client/node_modules/vscode-jsonrpc/lib/node/ril.js:90:29
	at new Promise (<anonymous>)
	at WritableStreamWrapper.write ($HOME/lsp-client-repro/lsp-sample-repro/client/node_modules/vscode-jsonrpc/lib/node/ril.js:80:16)
	at StreamMessageWriter.doWrite ($HOME/lsp-client-repro/lsp-sample-repro/client/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:100:33)
	at $HOME/lsp-client-repro/lsp-sample-repro/client/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:91:29
	at runNextTicks (internal/process/task_queues.js:58:5)
	at processImmediate (internal/timers.js:434:9)
	at process.callbackTrampoline (internal/async_hooks.js:131:14)
starts client and waits ready
didChangeState 1 -> 3
didChangeState 3 -> 2
waits for 3 seconds
stops client
didChangeState 2 -> 1
client stopped
waits for 2 seconds
rejected promise not handled within 1 second: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
stack trace: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
	at Socket.write (internal/streams/writable.js:292:11)
	at $HOME/lsp-client-repro/lsp-sample-repro/client/node_modules/vscode-jsonrpc/lib/node/ril.js:90:29
	at new Promise (<anonymous>)
	at WritableStreamWrapper.write ($HOME/lsp-client-repro/lsp-sample-repro/client/node_modules/vscode-jsonrpc/lib/node/ril.js:80:16)
	at StreamMessageWriter.doWrite ($HOME/lsp-client-repro/lsp-sample-repro/client/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:100:33)
	at $HOME/lsp-client-repro/lsp-sample-repro/client/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:91:29
	at runNextTicks (internal/process/task_queues.js:58:5)
	at processImmediate (internal/timers.js:434:9)
	at process.callbackTrampoline (internal/async_hooks.js:131:14)
starts client and waits ready
didChangeState 1 -> 3
didChangeState 3 -> 2
waits for 3 seconds
stops client
didChangeState 2 -> 1
client stopped
waits for 2 seconds
</details>

Note: I replaced prefix of absolute path with `$HOME`.

The server doesn't receive exit notification
because no file is created in my home directory.

## IPC

When I didn't change ServerOption, it works fine.
No error message appear. File is created in home diretory as exit notification is received.

**Comment by dbaeumer** [comment] 2021-12-10 15:18
@vain0x this got already addressed in the latest next versions of the library:
<img width="314" alt="capture" src="https://user-images.githubusercontent.com/1931590/145597370-11a5db39-bf40-4569-adef-0b78733d7c9f.png">

Server: 8.0.0-next.5 and client: 8.0.0-next.7

**Comment by dbaeumer** [comment] 2021-12-10 15:19
@mastevb any additional info?

**Comment by vain0x** [comment] 2021-12-11 05:35
Sorry, and thank for fix.

**Comment by dbaeumer** [comment] 2021-12-13 10:12
@mastevb will close the issue. Please ping if you have additional information.

**Closed by dbaeumer** 2021-12-13 10:12 UTC
Labels: needs more info
