### ISSUE TITLE
Support Yarn PnP module resolution

### ISSUE THREAD

**Issue by jgierer12** [microsoft/vscode-languageserver-node#496] opened 2019-06-07 17:32 UTC
The `Files.resolve` function exported by `vscode-languageserver` fails to resolve node modules in a [Yarn PnP](https://yarnpkg.com/en/docs/pnp) environment. This causes for example `vscode-eslint` to stop working when using PnP (see microsoft/vscode-eslint#601).

In order to support Yarn PnP, the project's local `.pnp.js` file needs to be required.

Quick pseudocode for how this should work:

```
if (is yarn pnp) {
  require(cwd + '/.pnp.js')
}

// ...rest
```

I think this has to be done at some point during the `app` script in `Files#resolve`:

https://github.com/microsoft/vscode-languageserver-node/blob/4d256255c2f2e00a2f6214c581e32ade7c8acc1e/server/src/files.ts#L52-L68

Edit: Or better yet, add `--require /path/to/.pnp.js` to the node CLI arguments here:

https://github.com/microsoft/vscode-languageserver-node/blob/4d256255c2f2e00a2f6214c581e32ade7c8acc1e/server/src/files.ts#L87-L90

That would be the [recommended approach](https://yarnpkg.com/en/docs/pnp/troubleshooting#toc-cannot-find-module) by the Yarn docs.

**Comment by dbaeumer** [comment] 2019-06-11 08:37
PR welcome. In the library this needs to be supported using an additional flag for the resolve function. 

The problem that I see is that on the consuming side how would a server know that something got installed using `yarn --pnp`. We would need another setting for this.

**Comment by tunnckoCore** [comment] 2019-06-11 10:38
> @jgierer12: Or better yet

Sounds great. So we will only need to specify the path to the .pnp file, which should default to cwd `./.pnp.js`

**Comment by Teoxoy** [comment] 2019-07-27 22:37
I am using yarn v2 (berry) for a monorepo, taking advantage of pnp and workspaces but `vscode-eslint` doesn't work because of this issue.

> The problem that I see is that on the consuming side how would a server know that something got installed using yarn --pnp. We would need another setting for this.

pnp comes by default with yarn v2 (berry). Regarding v1, I'm not sure how to check if pnp is enabled or not...

I would like to start a PR myself but there are some unknowns:

- should only yarn v2 be supported?
- how can this feature be tested?

**Comment by arcanis** [comment] 2019-07-28 10:09
> I'm not sure how to check if pnp is enabled or not...

For both v1 and v2, the best (automatic) way would be to check whether a `.pnp.js` file exist in the folder hierarchy (I have some hopes that in the future Node will support defining loaders through the package.json which would remove the need for this, but it won't be before at least a few years).

Note that the returned path will be stored within an archive (`/foo/eslint.zip/index.js`) - spawning the process will require to inject the PnP loader as well (although that might be something for https://github.com/microsoft/vscode-eslint/issues/601 rather than this issue?).

Tbh I'm not too sure how vscode-eslint is interlaced with vscode-languageserver-node (is it spawned? is it `require`-ed?) so I can't give the complete solution, but feel free to ask questions to better understand how VSCode would interact with PnP 😃

**Comment by Teoxoy** [comment] 2019-07-28 10:56
> Note that the returned path will be stored within an archive (/foo/eslint.zip/index.js) - spawning the process will require to inject the PnP loader as well (although that might be something for microsoft/vscode-eslint#601 rather than this issue?).

Can you clarify? I don't really understand what you mean here. Doesn't `--require /path/to/.pnp.js` solve this?

> Tbh I'm not too sure how vscode-eslint is interlaced with vscode-languageserver-node

https://github.com/microsoft/vscode-eslint/blob/master/server/src/eslintServer.ts#L444-L451
It uses `vscode-languageserver` (this package) to resolve eslint

https://github.com/microsoft/vscode-languageserver-node/blob/db16b7f53b318e8ff44aa95ac8faa5e2486b63aa/server/src/files.ts#L42

From what I can see `Files.resolve` loads in a snippet of JS that runs in a `ChildProcess` and returns the required module.

@jgierer12 proposed 2 ways to solve this in the issue body. I would go with option 2 (spawning the `ChildProcess` with `--require /path/to/.pnp.js`) because it's more elegant.

**Comment by Teoxoy** [comment] 2019-07-28 11:16
> For both v1 and v2, the best (automatic) way would be to check whether a .pnp.js file exist in the folder hierarchy (I have some hopes that in the future Node will support defining loaders through the package.json which would remove the need for this, but it won't be before at least a few years).

Is there a way to get the path to `.pnp.js` taking into account `.yarnrc.yml` config too? I would like to have `.pnp.js` inside the `.yarn` folder.

For yarn v2 (berry), I think using `yarn config --json` then looking for [`pnpPath`](https://yarnpkg.github.io/berry/configuration/yarnrc#pnpPath) would be an option.
Regarding v1, there doesn't seem to be a way to configure where `.pnp.js` goes.

**Comment by arcanis** [comment] 2019-07-29 09:30
> Is there a way to get the path to .pnp.js taking into account .yarnrc.yml config too?

Not without parsing the Yarn configuration file, which I'd advise against.

If that's something you really want (I'm not sure it has enough value, personally), I think the way to go would be to add a VSCode configuration setting that would point to the PnP file.

**Comment by arcanis** [comment] 2019-07-29 09:42
> Can you clarify? I don't really understand what you mean here. Doesn't `--require /path/to/.pnp.js` solve this?

Yes and no. The code you're referring to is meant to return the path to the ESLint JS script. In order to get this path, you have to use the PnP resolve indeed - using `--require` will be enough to do that.

However, the resolver will return you a path *within a zip archive*. Meaning that instead of having something like `/n_m/eslint/index.js`, you'll have something like `/eslint.zip/index.js`. In order for Node to be able to load this script, it'll have to be executed with the Yarn-generated loader as well - meaning that you'll also have to use `--require` when *executing* the file, not only obtaining its path. Does that make sense?

> From what I can see `Files.resolve` loads in a snippet of JS that runs in a `ChildProcess` and returns the required module.

If it's a child process then it's fairly easy - you just have to set the `NODE_OPTIONS` environment variable to `--require /path/to/.pnp.js` (or execute `yarn node <path/to/script.js>`) and it'll just work. The problem is that I think it's using `require` instead of a child process, in which case it will be a fair bit more difficult since injecting the PnP loader would modify the global environment (I'm a bit surprised though - isn't it a potential attack vector to run ESLint within the VSCode sandbox?):

https://github.com/microsoft/vscode-eslint/blob/3212f7cdacbb782f104872bb42141ca6c5a0dc26/server/src/eslintServer.ts#L211

**Comment by Teoxoy** [comment] 2019-07-29 11:42
> Does that make sense?

Yeah, thanks for the longer explanation!

> From what I can see Files.resolve loads in a snippet of JS that runs in a ChildProcess and returns the required module.

I need to correct myself on this one - it actually returns the path to the module and not the module itself.

This means that implementing pnp support in `Files.resolve` is not enough. Every library that uses this function would then have to implement their own pnp support.

Can't pnp support just be baked into node itself? Every lib I know of assumes that `require()` just works.

> I have some hopes that in the future Node will support defining loaders through the package.json which would remove the need for this, but it won't be before at least a few years

This would be perfect.

> The problem is that I think it's using require instead of a child process, in which case it will be a fair bit more difficult since injecting the PnP loader would modify the global environment

I would say instead of requiring trough `NODE_OPTIONS`, we just use the `--require` param of node when spawning the child process.

> https://github.com/microsoft/vscode-eslint/blob/3212f7cdacbb782f104872bb42141ca6c5a0dc26/server/src/eslintServer.ts#L211

This is where the actual modules are loaded. Is there a way to get a reference to the pnp require function? Does `.pnp.js` export something like this?

**Comment by arcanis** [comment] 2019-07-29 13:00
> Can't pnp support just be baked into node itself?

Not before years, I'd guess. The loader spec is the closest thing we'll have, and it's still in its infancy.

> Every lib I know of assumes that `require()` just works.

Calling `require` *does* just work - if you're doing it within the same runtime. The problem here is that `vscode-eslint` (a project that's running within the Electron runtime) is doing a `require` on a file from the user project (that's running within the PnP runtime). It's a very unusual pattern.

> This is where the actual modules are loaded. Is there a way to get a reference to the pnp require function? Does `.pnp.js` export something like this?

I think the solution that would have the best chance to succeed with the lowest cost would be to require ESLint within a sandbox, using the [`vm` module](https://nodejs.org/api/vm.html). This would allow to load the PnP runtime "globally", but keeping it scoped to the sandbox. The problem in this situation is to figure out how to setup the sandbox properly (so that the `Module` patches don't leak, for example). It's doable, but there's a bit of experiments to do there 🤔

**Comment by Teoxoy** [comment] 2019-07-29 13:18
> The problem here is that vscode-eslint (a project that's running within the Electron runtime) is doing a require on a file from the user project (that's running within the PnP runtime). It's a very unusual pattern.

I think it's done this way so that you can choose the eslint version and plugins you want to use.

> I think the solution that would have the best chance to succeed with the lowest cost would be to require ESLint within a sandbox, using the vm module.

This should work for the eslint plugins as well right? They can be loaded using the same node vm I guess.

I don't have any experience with the vm module for node. Would you be able to look into adding this to `vscode-eslint`?

I also think we should move the conversation regarding the specific `vscode-eslint` stuff to microsoft/vscode-eslint#601

**Comment by dbaeumer** [comment] 2019-08-06 14:47
Discussing this in the ESLint repository is the best location. It was a mistake to add the resolve feature to the server in the first place and I actually will not improve this further. Loading stuff from the workspace folder should be best done by the extension that wants to load these files. 

So I close the issue in favour of the having a solution in ESLint.

**Comment by dbaeumer** [comment] 2019-08-06 14:48
@Teoxoy and @arcanis thanks a lot for the enlightening discussion.

**Closed by dbaeumer** 2019-08-06 14:47 UTC
Labels: feature request, help wanted
