### ISSUE TITLE
Cannot read property 'Unnecessary' of undefined

### ISSUE THREAD

**Issue by georgewfraser** [Microsoft/vscode-languageserver-node#468] opened 2019-03-02 17:43 UTC
I'm sending this message on the LSP:

```
[Trace - 9:25:42 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///Users/georgefraser/Documents/java-language-server/src/test/test-project/workspace/src/org/javacs/warn/Unused.java",
    "diagnostics": [
        {
            "range": {
                "start": {
                    "line": 23,
                    "character": 4
                },
                "end": {
                    "line": 23,
                    "character": 33
                }
            },
            "severity": 4,
            "code": "unused",
            "message": "`UnusedClass` is not used",
            "tags": [
                1
            ]
        },
        {
            "range": {
                "start": {
                    "line": 12,
                    "character": 8
                },
                "end": {
                    "line": 12,
                    "character": 32
                }
            },
            "severity": 2,
            "code": "unused",
            "message": "`unusedLocalInLambda` is not used",
            "tags": [
                1
            ]
        },
        {
            "range": {
                "start": {
                    "line": 15,
                    "character": 4
                },
                "end": {
                    "line": 17,
                    "character": 5
                }
            },
            "severity": 4,
            "code": "unused",
            "message": "`unusedMethod` is not used",
            "tags": [
                1
            ]
        },
        {
            "range": {
                "start": {
                    "line": 6,
                    "character": 8
                },
                "end": {
                    "line": 6,
                    "character": 28
                }
            },
            "severity": 2,
            "code": "unused",
            "message": "`unusedLocal` is not used",
            "tags": [
                1
            ]
        },
        {
            "range": {
                "start": {
                    "line": 9,
                    "character": 4
                },
                "end": {
                    "line": 9,
                    "character": 30
                }
            },
            "severity": 2,
            "code": "unused",
            "message": "`unusedPrivate` is not used",
            "tags": [
                1
            ]
        },
        {
            "range": {
                "start": {
                    "line": 21,
                    "character": 4
                },
                "end": {
                    "line": 21,
                    "character": 29
                }
            },
            "severity": 4,
            "code": "unused",
            "message": "`<init>` is not used",
            "tags": [
                1
            ]
        }
    ]
}
```

But I'm not seeing any green squigglies or faded backgrounds, and I'm seeing this error in the VSCode debug console:

```
Notification handler 'textDocument/publishDiagnostics' failed with message: Cannot read property 'Unnecessary' of undefined
```

I'm running version 1.31.1 of VSCode. This is what my package.json looks like:

```
{
    "name": "vscode-javac",
    "displayName": "Java Language Support",
    "description": "Java support using the Java Compiler API",
    "icon": "icon.png",
    "version": "0.2.14",
    "publisher": "georgewfraser",
    "repository": {
        "type": "git",
        "url": "https://github.com/georgewfraser/java-language-server"
    },
    "license": "MIT",
    "engines": {
        "vscode": "^1.31.1"
    },
    "categories": [
        "Programming Languages",
        "Linters"
    ],
    "keywords": [
        "java"
    ],
    "activationEvents": [
        "onLanguage:java"
    ],
    "main": "./out/lib/extension",
    "contributes": {
        /* removed */
    },
    "scripts": {
        "vscode:prepublish": "npm run compile",
        "compile": "tsc -p ./",
        "watch": "tsc -watch -p ./",
        "postinstall": "node ./node_modules/vscode/bin/install",
        "test": "npm run compile && node ./node_modules/vscode/bin/test"
    },
    "dependencies": {
        "vscode-languageclient": "^5.3.0-next.1"
    },
    "devDependencies": {
        "typescript": "^3.3.3333",
        "vscode": "^1.1.21",
        "@types/node": "^10.3.3",
        "@types/mocha": "^2.2.42"
    }
}
```

**Comment by georgewfraser** [comment] 2019-03-02 18:05
After a little more investigation, I suspect the problem is that you need to published a new version `3.15.0-next` of `vscode-languageserver-protocol` which declares a dependency on `3.14.0` of [vscode-languageserver-types](https://github.com/Microsoft/vscode-languageserver-node/tree/9de8809400b7c443bc25f211dfaddcb74675b2d7/types) but actually requires the latest code which has not been published.

**Comment by Gama11** [comment] 2019-03-11 15:23
Looks like the `3.15.0-next.2` that was just published still depends on outdated `types` (cc @dbaeumer).

**Comment by dbaeumer** [comment] 2019-03-13 10:19
Actually I can't reproduce this in a dev environement.

**Comment by dbaeumer** [comment] 2019-03-13 10:25
Ignore my last comment. It is a broken types dependency. Sorry for that.

**Comment by dbaeumer** [comment] 2019-03-13 10:39
Fixed by publishing new next versions.

**Closed by dbaeumer** 2019-03-13 10:39 UTC
