### ISSUE TITLE
Error: spawn EINVAL when starting the Language Server

### ISSUE THREAD

**Issue by tiltue** [microsoft/vscode-languageserver-node#1545] opened 2024-08-16 09:40 UTC
I get the following error when I start my extension: 
![image](https://github.com/user-attachments/assets/b6ad2952-92a5-448a-bf7e-5961092ac75f)

I already tried many different versions of all components, but nothing seems to work. 
I am currently working with:
"@types/node": "^14.14.14",  
"vscode-languageclient": "^7.0.0", 
"vscode": "^1.1.37",
"@types/vscode": "^1.89.0"
This configuration used to work a few weeks ago, but suddenly with no noticeable changes I got this error....
Does anyone experience the same issue? Any help is highly appreciated.

**Comment by dbaeumer** [comment] 2024-08-19 07:38
In which language is the server written. Usually an error like this points to an invalid path.

**Comment by tiltue** [comment] 2024-08-19 09:54
Thank you very much for your answer. The server is written in Scala. What kind of invalid path?

**Comment by tiltue** [comment] 2024-08-19 10:05
I also opened another issue [here](https://github.com/microsoft/language-server-protocol/issues/2005), since I got a different error message after trying some different versions of the npm packages.

**Comment by raycar5** [comment] 2024-08-19 11:10
likely related to https://github.com/nodejs/node/issues/52554 I'm running into the same issue with the kotlin language server, a different cursor installation with an older version of node (20.9) works but vscode with node version 20.14 does not

**Comment by raycar5** [comment] 2024-08-19 11:13
I have just installed vscode 1.92 and the error is gone

**Comment by tiltue** [comment] 2024-08-19 12:15
Thank you very much for your recommendation, I tried those versions but unfortunately, it is not working for me...

**Comment by raycar5** [comment] 2024-08-19 12:51
@tiltue try 1.91, I accidentally wrote 1.92 on my last message, which is the latest version and obviously not what I meant, sorry 😅

**Comment by dbaeumer** [comment] 2024-08-20 14:51
@raycar5 thanks for the pointers. We (in VS Code) got actually hit by this as well ;-)

**Comment by dbaeumer** [comment] 2024-08-20 14:51
I will close the issue since this is caused by NodeJS itself.

**Closed by dbaeumer** 2024-08-20 14:51 UTC
Labels: info-needed
