### ISSUE TITLE
Converter.asCompletionItem does not populate textEdit property on LSP CompletionItem

### ISSUE THREAD

**Issue by daytonellwanger** [microsoft/vscode-languageserver-node#449] opened 2019-01-10 01:09 UTC
The LSP spec recommends the `textEdit` property over the `insertText` property on a `CompletionItem` "since it avoids additional client side interpretation." However, the converter provided by the vscode-languageclient package does not set the `textEdit` property on the converted `CompletionItem`. [This condition](https://github.com/Microsoft/vscode-languageserver-node/blob/eba513161a8482ea275f8314ff6aa5c47879f4db/client/src/codeConverter.ts#L381) will always evaluate to `false` because there is no `fromEdit` property on a VS Code `CompletionItem`, so `textEdit` is never assigned to the LSP `CompletionItem`. Why is the `source.fromEdit` check included?

**Comment by lostintangent** [comment] 2019-01-10 06:56
@dbaeumer Is this something we could workaround? It’s a pretty non-ideal regression for Live Share (this impacts the guest when typing), and we’ve begun to hear bug reports pretty frequently about it.

**Comment by daytonellwanger** [comment] 2019-01-10 17:48
@lostintangent we could write our own `asCompletionItem` converter that is mostly a copy of the one provided by `vscode-languageclient` until this is fixed.

**Comment by daytonellwanger** [comment] 2019-01-10 18:23
A quicker hack would be for us to add a non-falsey `fromEdit` property to our completion items before converting them.

**Comment by dbaeumer** [comment] 2019-01-16 09:43
@daytonellwanger the code is actually written for a `ProtocolCompletionItem` and not a `CompletionItem` which has the fromEdit property always assigned. The code assumes that a client only sends back completion items it has received beforehand and the are converted into a `ProtocolCompletionItem` (which is a subclass of a completion item) here: https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/protocolConverter.ts#L355

The right fix would be to check in the code converted if the value is a `CompletionItem` and then do some other conversion code.

**Comment by dbaeumer** [comment] 2019-01-16 09:49
@daytonellwanger @lostintangent IMO the right workaround would be to not call the method at all and write your own conversion code for now since as said it assumes that the completion item is of type `ProtocolCompletionItem ` which has more additional properties:

```
export default class ProtocolCompletionItem extends code.CompletionItem {

	public data: any;
	public fromEdit: boolean;
	public documentationFormat: string;
	public originalItemKind: proto.CompletionItemKind;
	public deprecated: boolean;

	constructor(label: string) {
		super(label);
	}
}
```

I am open to doing this in the library as well but that will require a new release.

I am a little bit puzzled that this shows up now. The code is like that for a long time.

**Comment by dbaeumer** [comment] 2019-01-16 09:53
May be some background why we do this: the spec defines more attributes then VS Code supports (for example deprecated, data field, ...) and deals partly different with text edits. Since completion items in the LSP sense can flow from the client to the server as well (in the resolve call) we keep all the additional information in a `ProtocolCompletionItem` to be able to reconstruct a correct LSP completion item. However this is not the case in Live Share.

When you call the conversion method didn't TS flag this as an error?

**Comment by dbaeumer** [comment] 2019-01-16 09:55
Marking as feature request to add a conversion of a raw completion item.

**Comment by dbaeumer** [comment] 2019-01-16 09:56
Please also note that the same problem might exist for `DocumentLink` and `CodeLens` since we do the same trick here as well.

**Closed** 2019-10-28 16:19 UTC
Labels: *out-of-scope, feature request
