### ISSUE TITLE
Unregistering semantic token does not fall back to original highlighting

### ISSUE THREAD

**Issue by stamblerre** [microsoft/vscode-languageserver-node#691] opened 2020-11-17 23:14 UTC
I would expect that unregistering the `textDocument/semanticTokens` capability would change the highlighting back to the original implementation, but it doesn't seem to switch back to the default VS Code highlighting--it appears to still be using the server's highlighting.

**Comment by dbaeumer** [comment] 2020-11-18 13:10
@alexdima I debugged my code and when semantic tokens get unregistered in LSP I basically dispose the provider I registered (e.g. I call dispose on the Disposable returned from `registerDocumentSemanticTokensProvider`). Is there anything else I need to do or is this a bug on VS Code side?

**Comment by dbaeumer** [comment] 2020-11-26 08:04
@alexdima can you please comment.

**Comment by dbaeumer** [comment] 2020-12-03 13:39
Ping @alexdima

**Comment by alexdima** [comment] 2020-12-03 14:25
Duplicate of https://github.com/microsoft/vscode/issues/97196

**Closed by alexdima** 2020-12-03 14:25 UTC
Labels: needs more info

**Comment by dbaeumer** [comment] 2020-12-03 16:47
@alexdima thanks!
