### ISSUE TITLE
How does one package, or "export", a language server in `server/src/server.ts` for use with other editors?

### ISSUE THREAD

**Issue by hamirmahal** [microsoft/vscode-languageserver-node#856] opened 2021-11-20 18:28 UTC
I'd like to package or "export" `server/src/server.ts` so that I can use it with other LSP-compliant editors. How do I go about that?

**Comment by rcjsuen** [comment] 2021-11-22 13:31
@hamirmahal Not sure I totally understand your question. It seems to me like you should package and publish your server to an npm registry. That is what I do and my language server is used by other editors like Emacs, Vim, and Sublime.

**Comment by hamirmahal** [comment] 2021-11-22 18:07
@rcjsuen I see. So, I'm unclear on how to do those sub-steps. How does one package and publish the server to an `npm` registry, given [the VSCode LSP example template](https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-sample), which has `client` and `server` subdirectories?

From there, I'm not entirely sure how to make my published language server on `npm` work with Vim, Atom and Sublime.

Also, thank you for your reply!

**Comment by rcjsuen** [comment] 2021-11-22 19:11
> How does one package and publish the server to an `npm` registry, given [the VSCode LSP example template](https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-sample), which has `client` and `server` subdirectories?

That shouldn't be relevant. There's a `package.json` file in your `server` folder so you should be able to run [`npm publish`](https://docs.npmjs.com/cli/v8/commands/npm-publish/) without any issues. I don't have this setup as I just maintain a language server but it really shouldn't matter what your folder structure is like assuming your code is setup correctly and everything.

> From there, I'm not entirely sure how to make my published language server on `npm` work with Vim, Atom and Sublime.

Every LSP client has its own way of hooking into things. You'd have to follow up with each project to make sure it works well (if you so desire). For me personally, these editors have just hooked up with my language server themselves without asking me any questions for the most part. My interactions with them are generally related to integration bugs that are raised.

**Comment by dbaeumer** [comment] 2021-11-23 07:51
@rcjsuen thanks for providing these clarifications.

I will close the issue as a questions since there is no coding necessary in this repository. 

@hamirmahal you can continue the discussion even if the issue is closed.

**Closed by dbaeumer** 2021-11-23 07:51 UTC

**Comment by hamirmahal** [comment] 2021-12-17 00:05
Okay, so I've done `npm publish`, but

> For me personally, these editors have just hooked up with my language server themselves without asking me any questions for the most part.

this has not been the case. In Neovim, for example, I don't see the 'auto-complete' functionality we've added in our language server.

What things did you do to have the editors just hook up, by themselves?

**Comment by rcjsuen** [comment] 2021-12-17 02:23
> > For me personally, these editors have just hooked up with my language server themselves without asking me any questions for the most part.
> 
> this has not been the case. In Neovim, for example, I don't see the 'auto-complete' functionality we've added in our language server.
> 
> What things did you do to have the editors just hook up, by themselves?

What I meant is I do not test my language server in most LSP editors. I rely on the community to take my language server and add the necessary hooks so it works for their favourite editors. If no one does this work for some editor X that's too bad but I do not spend my time checking every editor to ensure that my language server is working properly. I depend solely on the community to open bugs to let me know if my language server is being non-compliant with the LSP specification.

**Comment by hamirmahal** [comment] 2021-12-21 03:35
Ah, okay. Thank you for the clarification.
