### ISSUE TITLE
Killing a child process on the server side crashes VSCode

### ISSUE THREAD

**Issue by Ptival** [microsoft/vscode-languageserver-node#757] opened 2021-04-14 02:21 UTC
VSCode:
1.55.2
3c4e3df9e89829dce27b7b5c24508306b151f30d
x64

OS: macOS Big Sur 11.2.3 (20D91)

Steps to reproduce:
- create a long-standing child process using either `ChildProcess.execFile` or `ChildProcess.spawn`, trying from either the client side or the server side
- after some time, `kill()` the process

Expected: the process dies in both cases

Actual:
- from the client, nothing bad seems to happen
- when the server one is killed, the whole VSCode goes down with `the window has crashed (reason 'killed')`

Is there something to do to prevent that?

**Comment by dbaeumer** [comment] 2021-04-14 11:52
@Ptival what you could try is to run the server using a custom node and not the node version that ships with VS Code.

@deepak1556 @bpasero any idea why this is happening? I suspect that the process spawned is an electron node process. TO we somehow monitor those?

**Comment by bpasero** [comment] 2021-04-14 12:03
Sorry but those steps to reproduce are not helpful for me, please provide step by steps instructions that I can follow through.

**Comment by Ptival** [comment] 2021-04-15 01:02
I'm still trying to create a reproducible version of it. Depending on what command I try to execute, it does not crash VSCode, and the one that I can reliably make crash relies on a setup that is too complex to reproduce.

My reproduction setup is otherwise super simple, I just cloned the vscode-extensions-sample, and added the following to `server.ts`:

```typescript
import * as ChildProcess from 'child_process'
import * as fs from 'fs'
import * as os from 'os'
import * as path from 'path'
```

and somewhere in the `validateTextDocument` method I drop:

```typescript
const command = ...
const options = [...]
const timeout = ...

const p = ChildProcess.execFile(command, options)
setTimeout(() => p.kill(), timeout)
p.stdout?.on('data', (d) => connection.window.showInformationMessage(d))
```

Now the choice of `command`, `options`, and `timeout` that make VSCode crash is where I'm having trouble finding a reproducible setup.
Notably, simple Unix commands like `yes` or `sleep` have not yet allowed me to reproduce the error.
Even on my failing command, the choice of `timeout` can make the error go away. It seems to happen more reliably for small values like `100`.

If it helps, I found a relevant crash log (`Application Support/Code/logs/20210414T175050/renderer1.log`):
```
[2021-04-14 17:50:50.659] [main] [info] update#setState idle
[2021-04-14 17:51:20.678] [main] [info] update#setState checking for updates
[2021-04-14 17:51:20.927] [main] [info] update#setState idle
[2021-04-14 17:53:10.267] [main] [error] CodeWindow: renderer process crashed (detail: killed)
[2021-04-14 17:53:10.379] [main] [error] [uncaught exception in main]: Error: SharedProcess: crashed (detail: killed)
[2021-04-14 17:53:10.379] [main] [error] Error: SharedProcess: crashed (detail: killed)
    at /nix/store/h0vvl0dq11hfqy37dhxwm8zgkdjhbj6k-vscode-1.55.0/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:56:68768
    at E.fire (/nix/store/h0vvl0dq11hfqy37dhxwm8zgkdjhbj6k-vscode-1.55.0/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:16:1836)
    at /nix/store/h0vvl0dq11hfqy37dhxwm8zgkdjhbj6k-vscode-1.55.0/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:14:47011
    at E.fire (/nix/store/h0vvl0dq11hfqy37dhxwm8zgkdjhbj6k-vscode-1.55.0/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:16:1836)
    at Object.<anonymous> (/nix/store/h0vvl0dq11hfqy37dhxwm8zgkdjhbj6k-vscode-1.55.0/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:55:9352)
    at Object.emit (events.js:327:22)
[2021-04-14 17:53:10.381] [main] [error] CodeWindow: renderer process crashed (detail: killed)
```

I'll update if I find some way to crash it with readily available executables.

**Comment by deepak1556** [comment] 2021-04-15 02:16
Can you follow these steps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports and attach the crash reports. Thanks!

**Comment by Ptival** [comment] 2021-04-15 02:50
No dump file, just three empty directories and a `settings.dat`.

Note that when I say VSCode crashes, it actually stays open with a window `The window has crashed (reason: 'killed')` letting me choose whether to Close or Reopen.
I get two such pop-ups: one for the original editor, one for the debugging editor.

**Comment by deepak1556** [comment] 2021-04-15 03:33
Nevermind, I missed the reason was killed rather than a crash. Can you launch the app with the following and attach the output from terminal once the window gets killed. The output will contain verbose information about child process calls which will print details of your env, if you think they are sensitive you can instead send the logs to Deepak.Mohan@microsoft.com

`NODE_DEBUG='child_process' code --verbose`

**Comment by Ptival** [comment] 2021-04-15 04:59
It's too long to post as a Github comment, but here it is, hopefully with no critical private information:
https://gist.github.com/Ptival/64646dded680449ce6d4635ed09fbc62

It will be very clear in this log that I am using nix to install VSCode, if that is relevant to this situation!

**Comment by deepak1556** [comment] 2021-04-15 19:51
Thanks for the logs, after the lsp server spawn call https://gist.github.com/Ptival/64646dded680449ce6d4635ed09fbc62#file-vscode-log-L2342 I only see some git calls before shutdown. What is the child process call that you had created ?

**Comment by Ptival** [comment] 2021-04-15 20:11
Oh, thanks to you I found the source of the problem!

The process I am launching is a research tool, which I have now found, in its setup, installs a signal handler for the SIGTERM signal that broadcasts the signal to its entire process group!

It is actually now very easy to reproduce, for instance, by using the following Python "group murder" script:
```python
#! /usr/bin/env python
import os, signal
os.killpg(os.getpgid(os.getpid()), signal.SIGTERM)
```
If you run this script in the language server, it brings down all VSCode instances.

In this light, it actually seems moderately reasonable to not expect the language server to sandbox this entirely.
I'll leave it up to you to decide whether you want this behavior to be prohibited entirely, or whether to close the issue.

**Comment by deepak1556** [comment] 2021-04-15 20:34
That makes sense :)

I don't think we have to selectively sandbox this scenario given the nature of extension host. Closing for now, @dbaeumer feel free to reopen if you think this deserves further attention.

**Closed by deepak1556** 2021-04-15 20:34 UTC
Labels: needs more info
