### ISSUE TITLE
Tracking deleted files from a folder which is deleted

### ISSUE THREAD

**Issue by angelozerr** [microsoft/vscode-languageserver-node#1317] opened 2023-09-14 17:08 UTC
We have a language server which need to track deleted files (**/**/*.html files) 
To do that we use `workspace/didChangeWatchedFiles` which is working great when user delete html files.

The problem comes from when a folder which contains html files are deleted.

 * on Windows OS with vscode, the language server receives the deleted folder only. In this case, how to retrieved the deleted files from the deleted folder?
 * on Mac OS with vscode,  the language server receives the all deletedhtml files.

My first question is it an expected behavior (I mean a different behavior between 2 OS) ?

I discover the [workspace/didDeleteFiles notification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didDeleteFiles), what is the difference from the [workspace/didChangeWatchedFiles](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeWatchedFiles)

Many thanks for your clarification!

**Comment by rgrunber** [comment] 2023-09-15 14:11
According to https://github.com/microsoft/vscode-languageserver-node/issues/141#issuecomment-271296153 , the behaviour should be to only notify that the folder has been deleted in all cases. So this has regressed now it seems. The language client should try to protect against inconsistent behaviour across different platform.s

**Comment by dbaeumer** [comment] 2023-09-18 10:08
@bpasero I get these events 1:1 from VS Code. Is this expected?

**Comment by bpasero** [comment] 2023-09-18 10:48
Yes, it is expected that we do not send out delete events for each entry of a folder because listeners can easily figure out if a path is a child of said path and we can reduce the amount of events we have to send around:

https://github.com/microsoft/vscode/blob/d932af32771f4fcb8bef171f3114dfbd06ec5bed/src/vs/platform/files/common/watcher.ts#L377-L403

However, we rely on the operating system to give us the actual file events and our normalization of events works by accumulating events over some short period. If the OS gives us events slowly, above the threshold, we might start to send out individual deletes. 

File events can be logged when you run `code --verbose` and look for `[File Watcher (parcel)]` entries in the developer tools console:

![image](https://github.com/microsoft/vscode-languageserver-node/assets/900690/93999ed0-a073-4b16-8c0c-a60776c2118d)

**Comment by michprev** [comment] 2024-06-30 21:34
I am receiving no event(s) at all after deleting a directory containing `*.sol` file(s) with the watchdog configured as:

```python
FileSystemWatcher(
    glob_pattern="**/*.sol",
    kind=None,
),
```

Is this an expected behavior?

My VS Code setup:
```
Version: 1.90.2
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:54:35.075Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0
```

**Comment by dbaeumer** [comment] 2024-07-01 08:15
As @bpasero pointed out we only send out events for the folder when a folder gets deleted. So you need to register for folder deletions as well.

**Comment by dbaeumer** [comment] 2024-12-09 08:54
I will close the issue since this is how VS Code works in terms of file events.

**Closed by dbaeumer** 2024-12-09 08:54 UTC
Labels: info-needed
