### ISSUE TITLE
NPE in protocolConverter.asHover

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-languageserver-node#207] opened 2017-05-16 14:47 UTC
The Java language server fails with
```
    at new e (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:227228)
    at asHover (/home/aeschli/.vscode-insiders/extensions/redhat.java-0.4.0/node_modules/vscode-languageclient/lib/protocolConverter.js:63:16)
e.onUnexpectedError @ workbench.main.js:29
```
when hovering over a symbol without hover.

The reason is that it returns an empty hover object, without the 'contents' field.
I guess strictly speaking this might be a server issue, but IMO it would be ok to be tolerant in the language client and just ignore all hovers without the 'contents' field.
https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/protocolConverter.ts#L176

**Comment by martijnwalraven** [comment] 2017-11-16 20:37
Looking at the code, it seems the intention is to return `null` (or `undefined`) when there is no hover to be returned, not a hover without contents.

The problem is that `onHover` is defined to respond with `Hover`:
```typescript
onHover(handler: RequestHandler<TextDocumentPositionParams, Hover, void>): void;
```

Maybe this should be:
```typescript
onHover(handler: RequestHandler<TextDocumentPositionParams, Hover | null, void>): void;
```

**Comment by dbaeumer** [comment] 2017-11-17 09:47
@martijnwalraven I fixed this a couple of days ago to make it more clear. With be in the next release.

@aeschli I am closing the issue. I am against swallowing an incorrect hover since it will lead to new issue claiming that a server returns a hover but the UI is not showing it. It would be like asking the VS Code API allow Hovers without content and not showing it.

I would recommend that the Java server implements data checking on their end to better discover this mismatches.

**Closed by dbaeumer** 2017-11-17 09:47 UTC
Labels: bug

**Comment by martijnwalraven** [comment] 2017-11-17 09:56
@dbaeumer Thanks! It seems [`master` still has `onHover` without `null`](https://github.com/Microsoft/vscode-languageserver-node/blob/1a780aec55f79c60fe98a4081640ffe19fc0d400/server/src/main.ts#L1144). Or is this in a separate branch?

**Comment by martijnwalraven** [comment] 2017-11-17 09:57
(I also think `onSignatureHelp` has the same issue.)

**Comment by dbaeumer** [comment] 2017-11-17 10:56
Good catch. I only updated 
https://github.com/Microsoft/vscode-languageserver-node/blob/master/protocol\src\protocol.ts#L1279

Will do the others as well.

**Comment by dbaeumer** [comment] 2017-11-17 11:14
Done.
