### ISSUE TITLE
Any example of consuming the server from an external Java application?

### ISSUE THREAD

**Issue by scela** [Microsoft/vscode-languageserver-node#47] opened 2016-06-14 10:50 UTC
Is there any example on how to consume the services provided by the server from a detached java application ? Concretely we're talking about an eclipse plugin sending requests and receiving responses to this server and use the information to autocomplete/color editors etc.

If not, any hint on how to connect to the server from an external application (through stdio sockets etc.) ?

**Comment by dbaeumer** [comment] 2016-06-15 09:04
I am not aware of any public available example. However I do know that Eclipse Che (@TylerJewell) is working on a client in Java. May be you can join forces. 

There is a specification of the protocol here: https://github.com/Microsoft/vscode-languageserver-protocol which should help implementing the protocol for a different client.

@scela ok to close this issue.

**Comment by mickaelistria** [comment] 2016-06-16 09:29
@dbaeumer Thanks for this answer. Is there a way to start the server as a "deamon" that remains active and to whom other processes (such as Eclipse IDE) can connect via socket or streaming data from/to the stdout/stdin of this process?

**Comment by TylerJewell** [comment] 2016-06-16 09:32
@mickaelistria - each language server will operate itself in its own configuration. So you can expect a wide range of server execution types.  The Java language bindings that Che is using to map to the protocol are located at [Sven's](https://github.com/TypeFox/ls-api) repository.  Finally, Codenvy is working on a public registry for language servers that will have a variety of features around discovery, updating, and downloading language servers for execution with a tool.  We'll be publishing the requirements for this as an Eclipse project.

**Comment by mickaelistria** [comment] 2016-06-20 13:04
Thanks for your answers but they're not exactly answering the question I have in mind (most likely because I was not clear asking it). I'll try a variation of the question:
Assuming I have VSCode started; is there a way to identify which one of the subprocesses and/or sockets are actually interfaces with the language server? Once we have one or the other, we can then try to communicate with it using https://github.com/TypeFox/ls-api , but at the moment, I'm failing at finding the streams to pass to the Java client without starting my own server.

**Comment by dbaeumer** [comment] 2016-06-21 08:25
@mickaelistria yes this is possible. However the server would need to handle the causes that more then one edtitor (even different products) connect to that server. 

The client library we ship can be configures with a readable and writeable stream instead of an exexcutable to launch. See interface StreamInfo for details. However the client library has means to manage demon language servers.

**Comment by scela** [comment] 2016-06-22 11:58
Not sure how running an additional external client is different from having two javascript editors simultaneously in vscode from the 'more than one editor connect to the server' POV. If there is, why make it a server-client in the first place.

The StreamInfo and ServerOptions are concepts on a higher level (language level) than we need. When we talk about server-client communication, we mean on some ip, on some port, something serves a stream which accepts requests and answers in a certain protocol. We want to interface with this server in Java code, so the js-level abstractions are of no use in this case. We have our own implementation of the protocol  in Java (ls-api that Mickael mentioned) but it seems there is no way we can interface with this server easily from the classical server point of view.

**Comment by dbaeumer** [comment] 2016-06-23 08:46
@scela I am not sure I understand your question correctly. A try to answer it:

The base protocol that defines how to read and write messages from the stream and decode them is defined here: https://github.com/Microsoft/vscode-languageserver-protocol#base-protocol. Do you see any limitations to implement the protocol in Java?

The current assumption with language servers is that two workspaces have two instances of the language server running. We haven't invested into language services that can be looked up and reused. However doing this using the protocol should absolutely be possible.

**Comment by mickaelistria** [comment] 2016-06-23 08:54
> Do you see any limitations to implement the protocol in Java?

We are not trying to implement this protocol in Java, we're trying to use the Java client from Typefox to consume the language server of VSCode. Java API for Language Server can connect directly to existing streams. What we're stuck at is determing which strings to use to connect to the language server running with VSCode (assuming it's already started on the machine).

> The current assumption with language servers is that two workspaces have two instances of the language server running.

What we're trying to more to get 2 distinct clients (VSCode and Eclipse) connecting to the same server, using either the same workspace or 2 different ones on the same server. Eclipse would only be in charge of "connecting" to an existing server, not of starting one.

> We haven't invested into language services that can be looked up and reused. However doing this using the protocol should absolutely be possible. 

Ok, thanks. That's the area we're interested in exploring.
If VSCode uses stdin/stdout, we can simply connect to the related File Streams on Linux (not a solution but a way forward), if it's happening via Socket, we may be able to also connect to it. The problem we've been facing is how to identify which PID is the language server (in case of stdin/stdout) or which socket it's using.

**Comment by dbaeumer** [comment] 2016-06-23 13:11
@mickaelistria ok. Now I understand what you try to achive. My statement in the last comment that the protocol should enable this is actually not true (@egamma thanks for pointing this out to me). The problem is that opening a text document transfers the ownership of the document's content to the client (e.g VS Code). If now in your setup the same document gets opened in both VS Code and Eclipse the ownership is not clear anymore. The document's content can't be owned by Eclipse and VS Code. and what happens if the user starts to type in both editors. To make your scenario work the server must provide some sort of concurrent editing infrastructure which it currently doesn't.

**Comment by mickaelistria** [comment] 2016-06-23 13:19
@dbaeumer thanks for your answer. I was expecting this kind of limitation about synchronization/concurrence. And let's imagine that VSCode and Eclipse working on distinct set of files; in the current state, could we imagine Eclipse consuming the LS from VSCode for its own files? This doesn't solve the concurrence issue, I'm just trying to evaluate whether the approach of connecting to a Language Server deamon (such as VSCode started but not in use) can work in general.

**Comment by dbaeumer** [comment] 2016-06-27 12:19
@mickaelistria yes, it can work in general since the protocol itself doesn't make any assumption about the actual transport. The transport is current 'pluggable' in the node implementation we use for VS Code. So we can easily talk to a server which listens on a socket/port.

However one major reason for us investing into language servers is to have isolation as well. We noticed for example that a single workspace can put quite some stress onto a language server. To avoid the noisy neighbor problem we currently don't share servers between workspace instances.

**Comment by smarr** [comment] 2016-07-06 21:59
I got a first working connection between VS code and a Java server using this [proxy.js](https://gist.github.com/smarr/79c1a5e90c9a13659f38597e44caa568) in the VS Code extension.
The `stdio` communication support seems to be broken. I got only the node.js IPC based version to work.

The proxy.js uses it to connect then to the ls-api implementation in Java by using VS Code's stream reader/writer support, which is connected via stdin/stdout.

**Comment by mickaelistria** [comment] 2016-07-06 22:13
cc @gorkem

**Comment by smarr** [comment] 2016-07-06 22:32
Actually, never mind, after reading the types correctly, I figured out that a simple:

```
let serverOptions: ServerOptions = {
	command: 'run-java-server.sh'
}
```

in the extension does just fine, too.

**Comment by gorkem** [comment] 2016-07-07 01:31
@mickaelistria I am renewing the connection implementation on https://github.com/gorkem/java-language-server and implementing regular sockets in addition to the current named pipes. The plan is to also have a `LanguageClient` similar to what vscode API provides. Stay tuned it should not take long. :)

**Comment by dbaeumer** [comment] 2017-04-10 15:19
Is there anything that needs to be done from your point of view? The client library got a lot more flexible in terms of transports (e.g socket files and named pipes)

**Comment by mickaelistria** [comment] 2017-04-10 15:40
Sorry for no giving news about it.
For several month, we've been able to consume VSCode language servers in Java using the LSP4J APIs, and running VSCode servers from Java with `node /usr/share/code/resources/app/extensions/html/server/out/htmlServerMain.js --stdio` and connecting to the stdio streams. So I believe you can close this ticket, and thanks a lot for your assistance!

**Comment by dbaeumer** [comment] 2017-04-11 08:05
@mickaelistria thanks for getting back. Closing then.

**Closed by dbaeumer** 2017-04-11 08:05 UTC
Labels: question

**Comment by maxm007** [comment] 2017-05-19 18:58
Guys,  I'm really struggling to get the StreamInfo working for a remote language service.    I have a remote scala service that supports JSON RPC which I'm trying to get to implement the language service.    The vscode json rpc component has this StreamInfo , but how do I get the streams populated?  What do I put in there?  I tried using Request module,  Http module in nodejs to return streams, but I just can't get it to work.   I was wondering if someone could point me to a working example.

**Comment by dbaeumer** [comment] 2017-06-06 12:09
@maxm007 StreamInfo simply has two properties. A reader and a writer were reader is a NodeJS.ReadableStream and writer is a NodeJS.WriteableStream. This stream are then used to read and write date from and to the server process. In the easiest case thes is stdio from the server process. However using stdio has the disadvantage that log statements written to stdout on the server side will interfere with the protocol. That is why we recommend to use named pipes under Windows and socket files under Linux/Mac. The client library has support for this. You can simple use the TransportKind.pipe on the client side. The pipe name / socket file name is then passed to the server process using the --pipe  argument. The server has to connect to the same pipe / socket file. An example how this is all coded in Node can be found here: https://github.com/Microsoft/vscode-languageserver-node/blob/master/jsonrpc/src/pipeSupport.ts#L5
