### ISSUE TITLE
didChange is being sent before didOpen

### ISSUE THREAD

**Issue by bpringe** [microsoft/vscode-languageserver-node#1105] opened 2022-10-28 02:20 UTC
This seems to be causing the issue mentioned here: https://github.com/BetterThanTomorrow/calva/issues/1900.

The [spec says](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didChange):

> Before a client can change a text document it must claim ownership of its content using the [textDocument/didOpen](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didOpen) notification.

I do see that the time is the same second, but the didChange appears first so I'm guessing it came a fraction of a second earlier than didOpen.

```text
[Trace - 11:36:32 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///Users/pez/Projects/tests/minimal-deps/src/foo.clj",
        "version": 2
    },
    "contentChanges": [
        {
            "text": "(ns foo\n  (:require [clojure.string :as string]))\n\n(defn bar\n  []\n  (let [x 1]\n    x))"
        }
    ]
}


[Trace - 11:36:32 PM] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///Users/pez/Projects/tests/minimal-deps/src/foo.clj",
        "languageId": "clojure",
        "version": 1,
        "text": ""
    }
}
```

**Comment by dbaeumer** [comment] 2022-10-28 08:25
@bpringe which version are you using? This looks very similar to https://github.com/microsoft/vscode-languageserver-node/issues/968 which for addressed in 8.0.2 (looks like you are using full text document sync as well).

If you are on a version > 8.0.2 can you provide me with steps on how to reproduce this?

**Comment by bpringe** [comment] 2022-10-29 04:13
We're using 8.0.2.

Steps to reproduce are noted here: https://github.com/BetterThanTomorrow/calva/issues/1900#issue-1412718106.

The clojure-lsp server maintainer mentions the ordering issue here: https://github.com/BetterThanTomorrow/calva/issues/1900#issuecomment-1283122856.

If you need more details, let me know.

**Comment by dbaeumer** [comment] 2022-10-31 11:27
I was able to reproduce this (see test case https://github.com/dbaeumer/vscode-lsp-1105). It happens only under the following conditions:

- full text sync
- save of an untitled file where the language server is not yet started (e.g. doesn't handle untitled files)

**Closed** 2022-10-31 13:10 UTC
Labels: bug

**Comment by bpringe** [comment] 2022-11-02 03:05
Thanks for the fix!
